### ISSUE TITLE
Error building binutils

### ISSUE THREAD

**Issue by riyadparvez** [dslab-epfl/cloud9#18]
I'm getting the following error building binutils:

> gcc -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include
> -DLOCALEDIR="\"/home/riyad/src/cloud9/src/third_party/binutils-install/share/locale\""
> -Dbin_dummy_emulation=bin_vanilla_emulation  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Werror -g -O2 -MT objdump.o -MD -MP -MF .deps/objdump.Tpo -c -o objdump.o
> -DOBJDUMP_PRIVATE_VECTORS="" ./objdump.c common.cc: In member function ‘void gold::Symbol_table::do_allocate_commons_list(gold::Layout_,
> gold::Symbol_table::Commons_section_type,
> gold::Symbol_table::Commons_type_, gold::Mapfile_,
> gold::Symbol_table::Sort_commons_order)’: common.cc:225:51: error:
> typedef ‘Value_type’ locally defined but not used
> [-Werror=unused-local-typedefs]    typedef typename
> Sized_symbol<size>::Value_type Value_type;
>                                                    ^ common.cc:226:50: error: typedef ‘Size_type’ locally defined but not used
> [-Werror=unused-local-typedefs]    typedef typename
> Sized_symbol<size>::Size_type Size_type;
>                                                   ^ mv -f .deps/cond.Tpo .deps/cond.Po gcc -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd
> -I./config -I./../include -I./.. -I./../bfd -DLOCALEDIR="\"/home/riyad/src/cloud9/src/third_party/binutils-install/share/locale\""
> -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Werror -g -O2 -MT depend.o -MD -MP -MF .deps/depend.Tpo -c -o depend.o depend.c mv -f .deps/depend.Tpo .deps/depend.Po gcc -DHAVE_CONFIG_H -I.  -I.
> -I. -I../bfd -I./config -I./../include -I./.. -I./../bfd -DLOCALEDIR="\"/home/riyad/src/cloud9/src/third_party/binutils-install/share/locale\""
> -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Werror -g -O2 -MT dwarf2dbg.o -MD -MP -MF .deps/dwarf2dbg.Tpo -c -o dwarf2dbg.o dwarf2dbg.c cc1plus: all warnings being treated as errors make[4]: *_*
> [common.o] Error 1 make[4]: Leaving directory
> `/home/riyad/src/cloud9/src/third_party/binutils/gold' make[3]: ***
> [all-recursive] Error 1 make[3]: Leaving directory
> `/home/riyad/src/cloud9/src/third_party/binutils/gold' make[2]: ***
> [all] Error 2 make[2]: Leaving directory
> `/home/riyad/src/cloud9/src/third_party/binutils/gold' make[1]: ***
> [all-gold] Error 2

**Comment by stefanbucur** [comment]
What binutils revision are you building and what OS are you running on?

**Comment by riyadparvez** [comment]
Binutils is the same version from Cloud 9.
binutils-2.22.tar.bz2

I am using Linux Mint 17 (based on Ubuntu 14.04).

gcc version:

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.2-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) 
```

**Comment by stefanbucur** [comment]
Cloud9 has only been tested on Ubuntu 10.10 through 12.04. I presume this is an incompatibility between 14.04 and Binutils 2.22. Switching to a more recent version might help. Unfortunately I won't have time to work on this myself, but I'll be happy to accept patches.

**Comment by riyadparvez** [comment]
Thanks for replying.

I see two versions of building instructions for Cloud9; one is in your Cloud9 site and another is in Github. The issue I've encountered is from Cloud9 site. Which one do you recommend?

**Comment by stefanbucur** [comment]
The Cloud9 site should be the authoritative source. Where did you find the building instructions on Github?

**Comment by riyadparvez** [comment]
Here's the Github link: https://github.com/dslab-epfl/cloud9/blob/master/docs/setup.rst.

I've compiled with binutils 2.24. But I compiled against latest STP revision. The STP revision in `DEPS` in the Cloud9 doesn't compile on Ubuntu 14.04.

I couldn't compile `sockets.c` in POSIX runtime. Removing header file `netdb.h` generates other errors.

```
llvm[2]: Compiling sockets.c for Release+Asserts build
sockets.c:1919:5: error: conflicting types for 'getnameinfo'
int getnameinfo(const struct sockaddr *sa, socklen_t salen,
    ^
/usr/include/netdb.h:677:12: note: previous declaration is here
extern int getnameinfo (const struct sockaddr *__restrict __sa,
           ^
1 error generated.
```

**Comment by stefanbucur** [comment]
This happens because Cloud9's POSIX model was not updated for Ubuntu 14.04. You should manually fix the definitions of the conflicting types and function signatures in the model.
